version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./arquivos:/tmp
    links:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  logvolume01: {}