camel:
  springboot:
    main-run-controller: TRUE

spring:
  main:
    banner-mode: OFF
  datasource: 
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: mysecretpassword
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1
  sql:
    init:
      platform: postgres